# Generated by Django 5.1.4 on 2024-12-25 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_sending", models.DateTimeField(auto_now_add=True, verbose_name="Дата первой рассылки")),
                (
                    "end_sending",
                    models.DateTimeField(
                        blank=True,
                        help_text="Введите дату окончания рассылки",
                        null=True,
                        verbose_name="Дата окончания рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("launched", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        help_text="Выберите статус рассылки",
                        verbose_name="Статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "topic",
                    models.CharField(
                        help_text="Введите тему сообщения", max_length=150, verbose_name="Тема сообщения"
                    ),
                ),
                ("text", models.TextField(help_text="Напишите сообщение", verbose_name="Текст сообщения")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["topic"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите электронную почту", max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("full_name", models.CharField(help_text="Введите ФИО", max_length=150, verbose_name="ФИО")),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Напишите комментарий", null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="AttemptSending",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.DateTimeField(auto_now=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("not_success", "Не успешно")],
                        default="not_success",
                        verbose_name="Статус попытки",
                    ),
                ),
                ("response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mailing.mailing", verbose_name="Рассылка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["time"],
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                help_text="Выберите сообщение",
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Выберите получателей", to="mailing.recipient", verbose_name="Получатели"
            ),
        ),
    ]
