# Generated by Django 4.2.2 on 2024-12-26 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="attemptsending",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="attemptsending",
            name="response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера"),
        ),
        migrations.AlterField(
            model_name="attemptsending",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_sending",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания рассылки"),
        ),
    ]
