# Generated by Django 4.2.2 on 2024-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_recipient_owner_alter_attemptsending_mailing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="first_sending",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Начало рассылки"),
        ),
    ]
